version: 2.1

orbs:
  android: circleci/android@2.4.0
  ruby: circleci/ruby@2.1.1
  app-distribution: tadashi0713/app-distribution@1.0.11

jobs:
  lint:
    executor:
      name: android/android-docker
      resource-class: xlarge
      tag: 2023.11.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - run: ./gradlew lintDebug
      - android/save-gradle-cache

  unit_test:
    executor:
      name: android/android-docker
      resource-class: xlarge
      tag: 2023.11.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - run: ./gradlew testDebugUnitTest
      - android/save-gradle-cache
      - store_test_results:
          path: ./app/build/test-results/testDebugUnitTest

  integration_test:
    executor:
      name: android/android-machine
      resource-class: xlarge
      tag: 2023.11.1
    steps:
      - checkout
      - android/start-emulator-and-run-tests
      - store_test_results:
          path: ./app/build/outputs/androidTest-results/connected

  beta:
    executor:
      name: android/android-docker
      resource-class: xlarge
      tag: 2023.11.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - ruby/install-deps
      - run: bundle exec fastlane beta
      - android/save-gradle-cache
      - app-distribution/upload_android:
          path: app/build/outputs/apk/debug/app-debug.apk
      - app-distribution/comment_github_pr

workflows:
  main:
    jobs:
      - lint
      - unit_test
      - integration_test
      - beta:
          context:
            - mobile
            - app-distribution
