version: 2.1

# Orbs
orbs:
  android: circleci/android@1.0.3
  ruby: circleci/ruby@1.2.0

# Executors(DRY)
executors:
  docker_executor: # Docker Executor
    docker:
      - image: cimg/android:2021.12.1
    resource_class: xlarge # Resource Class

jobs:
  lint:
    executor: docker_executor
    steps:
      - checkout
      - android/restore-gradle-cache
      - run: ./gradlew lintDebug
      - android/save-gradle-cache

  unit_test:
    executor: docker_executor
    steps:
      - checkout
      - android/restore-gradle-cache
      - run: ./gradlew testDebugUnitTest
      - android/save-gradle-cache
      - store_test_results: # Upload Test Results(Test Insights)
          path: ./app/build/test-results/testDebugUnitTest

  unit_test_parallel:
    executor: docker_executor
    parallelism: 4
    steps:
      - checkout
      - android/restore-gradle-cache
      - run: |
            cd app/src/test/java
            CLASSNAMES=$(circleci tests glob "**/*Test.kt" \
              | sed 's@/@.@g' \
              | sed 's/.kt//' \
              | circleci tests split --split-by=timings --timings-type=classname)
            cd ../../../../
            GRADLE_ARGS=$(echo $CLASSNAMES | awk '{for (i=1; i<=NF; i++) print "--tests",$i}')
            echo "Prepared arguments for Gradle: $GRADLE_ARGS"
            ./gradlew testDebugUnitTest $GRADLE_ARGS -Pcircleci
      - android/save-gradle-cache
      - store_test_results: # Upload Test Results(Test Insights)
          path: ./app/build/test-results/testDebugUnitTest

  integration_test:
    executor:
      name: android/android-machine # Machine Executor
      resource-class: xlarge
    steps:
      - checkout
      - android/start-emulator-and-run-tests
      - store_test_results: # Upload Test Results(Test Insights)
          path: ./app/build/outputs/androidTest-results/connected

  beta:
    executor: docker_executor
    steps:
      - checkout
      - android/restore-gradle-cache
      - ruby/install-deps # Ruby(Fastlane)
      - run: bundle exec fastlane beta
      - android/save-gradle-cache

workflows:
  main:
    jobs:
      - lint
      - unit_test
      - unit_test_parallel
      - integration_test
      - beta:
          context: # Context
            - mobile
          filters: # Filter Branch
            branches:
              only:
                - master
